apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: laravel-cms
  namespace: laravel-cms
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: laravel-cms-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    # Application secrets
    - secretKey: APP_KEY
      remoteRef:
        key: personal/laravel-cms
        property: app_key

    # Database credentials
    - secretKey: DB_HOST
      remoteRef:
        key: personal/laravel-cms
        property: db_host
    - secretKey: DB_DATABASE
      remoteRef:
        key: personal/laravel-cms
        property: db_database
    - secretKey: DB_USERNAME
      remoteRef:
        key: personal/laravel-cms
        property: db_username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: personal/laravel-cms
        property: db_password

    # Redis credentials
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: personal/laravel-cms
        property: redis_password

    # Mail credentials
    - secretKey: MAIL_HOST
      remoteRef:
        key: personal/laravel-cms
        property: mail_host
    - secretKey: MAIL_PORT
      remoteRef:
        key: personal/laravel-cms
        property: mail_port
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: personal/laravel-cms
        property: mail_username
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: personal/laravel-cms
        property: mail_password
    - secretKey: MAIL_ENCRYPTION
      remoteRef:
        key: personal/laravel-cms
        property: mail_encryption
    - secretKey: MAIL_FROM_ADDRESS
      remoteRef:
        key: personal/laravel-cms
        property: mail_from_address

    # AWS/S3 credentials (Cloudflare R2)
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: personal/laravel-cms
        property: aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: personal/laravel-cms
        property: aws_secret_access_key
    - secretKey: AWS_BUCKET
      remoteRef:
        key: personal/laravel-cms
        property: aws_bucket
