apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage
  namespace: hannyprastya
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-iscsi
