apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hannyprastya

resources:
  - ../../base
  - laravel-hpa.yaml

patches:
  - target:
      kind: Deployment
      name: laravel-cms
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

images:
  - name: ghcr.io/hannyprastya/portfolio
    newName: ghcr.io/hannyprastya/portfolio
    newTag: main-2ed63c0-web
